// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type VxlanAgentXDPExternalRouteInfo struct {
	ExternalIfaceIndex      uint32
	ExternalIfaceMac        VxlanAgentXDPMacAddress
	ExternalIfaceNextHopMac VxlanAgentXDPMacAddress
	ExternalIfaceIp         VxlanAgentXDPInAddr
}

type VxlanAgentXDPInAddr struct{ S_addr uint32 }

type VxlanAgentXDPIpv4LpmKey struct {
	Prefixlen uint32
	Data      uint32
}

type VxlanAgentXDPMacAddress struct{ Addr [6]uint8 }

type VxlanAgentXDPMacTableEntry struct {
	ExpirationTimer     struct{ Opaque [2]uint64 }
	Ifindex             uint32
	_                   [4]byte
	LastSeenTimestampNs uint64
	BorderIp            VxlanAgentXDPInAddr
	_                   [4]byte
}

// LoadVxlanAgentXDP returns the embedded CollectionSpec for VxlanAgentXDP.
func LoadVxlanAgentXDP() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_VxlanAgentXDPBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load VxlanAgentXDP: %w", err)
	}

	return spec, err
}

// LoadVxlanAgentXDPObjects loads VxlanAgentXDP and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*VxlanAgentXDPObjects
//	*VxlanAgentXDPPrograms
//	*VxlanAgentXDPMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadVxlanAgentXDPObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadVxlanAgentXDP()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// VxlanAgentXDPSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type VxlanAgentXDPSpecs struct {
	VxlanAgentXDPProgramSpecs
	VxlanAgentXDPMapSpecs
}

// VxlanAgentXDPSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type VxlanAgentXDPProgramSpecs struct {
	VxlanAgentXdp *ebpf.ProgramSpec `ebpf:"vxlan_agent_xdp"`
}

// VxlanAgentXDPMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type VxlanAgentXDPMapSpecs struct {
	BorderIpToRouteInfoMap *ebpf.MapSpec `ebpf:"border_ip_to_route_info_map"`
	IfindexIsInternalMap   *ebpf.MapSpec `ebpf:"ifindex_is_internal_map"`
	InternalNetworks       *ebpf.MapSpec `ebpf:"internal_networks"`
	MacTable               *ebpf.MapSpec `ebpf:"mac_table"`
}

// VxlanAgentXDPObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadVxlanAgentXDPObjects or ebpf.CollectionSpec.LoadAndAssign.
type VxlanAgentXDPObjects struct {
	VxlanAgentXDPPrograms
	VxlanAgentXDPMaps
}

func (o *VxlanAgentXDPObjects) Close() error {
	return _VxlanAgentXDPClose(
		&o.VxlanAgentXDPPrograms,
		&o.VxlanAgentXDPMaps,
	)
}

// VxlanAgentXDPMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadVxlanAgentXDPObjects or ebpf.CollectionSpec.LoadAndAssign.
type VxlanAgentXDPMaps struct {
	BorderIpToRouteInfoMap *ebpf.Map `ebpf:"border_ip_to_route_info_map"`
	IfindexIsInternalMap   *ebpf.Map `ebpf:"ifindex_is_internal_map"`
	InternalNetworks       *ebpf.Map `ebpf:"internal_networks"`
	MacTable               *ebpf.Map `ebpf:"mac_table"`
}

func (m *VxlanAgentXDPMaps) Close() error {
	return _VxlanAgentXDPClose(
		m.BorderIpToRouteInfoMap,
		m.IfindexIsInternalMap,
		m.InternalNetworks,
		m.MacTable,
	)
}

// VxlanAgentXDPPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadVxlanAgentXDPObjects or ebpf.CollectionSpec.LoadAndAssign.
type VxlanAgentXDPPrograms struct {
	VxlanAgentXdp *ebpf.Program `ebpf:"vxlan_agent_xdp"`
}

func (p *VxlanAgentXDPPrograms) Close() error {
	return _VxlanAgentXDPClose(
		p.VxlanAgentXdp,
	)
}

func _VxlanAgentXDPClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed vxlanagentxdp_bpfeb.o
var _VxlanAgentXDPBytes []byte
