// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type VxlanAgentUnknownUnicastFloodingExternalRouteInfo struct {
	ExternalIfaceIndex      uint32
	ExternalIfaceMac        struct{ Addr [6]uint8 }
	ExternalIfaceNextHopMac struct{ Addr [6]uint8 }
	ExternalIfaceIp         VxlanAgentUnknownUnicastFloodingInAddr
}

type VxlanAgentUnknownUnicastFloodingInAddr struct{ S_addr uint32 }

// LoadVxlanAgentUnknownUnicastFlooding returns the embedded CollectionSpec for VxlanAgentUnknownUnicastFlooding.
func LoadVxlanAgentUnknownUnicastFlooding() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_VxlanAgentUnknownUnicastFloodingBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load VxlanAgentUnknownUnicastFlooding: %w", err)
	}

	return spec, err
}

// LoadVxlanAgentUnknownUnicastFloodingObjects loads VxlanAgentUnknownUnicastFlooding and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*VxlanAgentUnknownUnicastFloodingObjects
//	*VxlanAgentUnknownUnicastFloodingPrograms
//	*VxlanAgentUnknownUnicastFloodingMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadVxlanAgentUnknownUnicastFloodingObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadVxlanAgentUnknownUnicastFlooding()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// VxlanAgentUnknownUnicastFloodingSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type VxlanAgentUnknownUnicastFloodingSpecs struct {
	VxlanAgentUnknownUnicastFloodingProgramSpecs
	VxlanAgentUnknownUnicastFloodingMapSpecs
}

// VxlanAgentUnknownUnicastFloodingSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type VxlanAgentUnknownUnicastFloodingProgramSpecs struct {
	VxlanAgentUnknownUnicastFlooding *ebpf.ProgramSpec `ebpf:"vxlan_agent_unknown_unicast_flooding"`
}

// VxlanAgentUnknownUnicastFloodingMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type VxlanAgentUnknownUnicastFloodingMapSpecs struct {
	BorderIpToRouteInfoMap       *ebpf.MapSpec `ebpf:"border_ip_to_route_info_map"`
	IfindexIsInternalMap         *ebpf.MapSpec `ebpf:"ifindex_is_internal_map"`
	InternalIfindexesArray       *ebpf.MapSpec `ebpf:"internal_ifindexes_array"`
	InternalIfindexesArrayLength *ebpf.MapSpec `ebpf:"internal_ifindexes_array_length"`
	RemoteBorderIpsArray         *ebpf.MapSpec `ebpf:"remote_border_ips_array"`
	RemoteBorderIpsArrayLength   *ebpf.MapSpec `ebpf:"remote_border_ips_array_length"`
}

// VxlanAgentUnknownUnicastFloodingObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadVxlanAgentUnknownUnicastFloodingObjects or ebpf.CollectionSpec.LoadAndAssign.
type VxlanAgentUnknownUnicastFloodingObjects struct {
	VxlanAgentUnknownUnicastFloodingPrograms
	VxlanAgentUnknownUnicastFloodingMaps
}

func (o *VxlanAgentUnknownUnicastFloodingObjects) Close() error {
	return _VxlanAgentUnknownUnicastFloodingClose(
		&o.VxlanAgentUnknownUnicastFloodingPrograms,
		&o.VxlanAgentUnknownUnicastFloodingMaps,
	)
}

// VxlanAgentUnknownUnicastFloodingMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadVxlanAgentUnknownUnicastFloodingObjects or ebpf.CollectionSpec.LoadAndAssign.
type VxlanAgentUnknownUnicastFloodingMaps struct {
	BorderIpToRouteInfoMap       *ebpf.Map `ebpf:"border_ip_to_route_info_map"`
	IfindexIsInternalMap         *ebpf.Map `ebpf:"ifindex_is_internal_map"`
	InternalIfindexesArray       *ebpf.Map `ebpf:"internal_ifindexes_array"`
	InternalIfindexesArrayLength *ebpf.Map `ebpf:"internal_ifindexes_array_length"`
	RemoteBorderIpsArray         *ebpf.Map `ebpf:"remote_border_ips_array"`
	RemoteBorderIpsArrayLength   *ebpf.Map `ebpf:"remote_border_ips_array_length"`
}

func (m *VxlanAgentUnknownUnicastFloodingMaps) Close() error {
	return _VxlanAgentUnknownUnicastFloodingClose(
		m.BorderIpToRouteInfoMap,
		m.IfindexIsInternalMap,
		m.InternalIfindexesArray,
		m.InternalIfindexesArrayLength,
		m.RemoteBorderIpsArray,
		m.RemoteBorderIpsArrayLength,
	)
}

// VxlanAgentUnknownUnicastFloodingPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadVxlanAgentUnknownUnicastFloodingObjects or ebpf.CollectionSpec.LoadAndAssign.
type VxlanAgentUnknownUnicastFloodingPrograms struct {
	VxlanAgentUnknownUnicastFlooding *ebpf.Program `ebpf:"vxlan_agent_unknown_unicast_flooding"`
}

func (p *VxlanAgentUnknownUnicastFloodingPrograms) Close() error {
	return _VxlanAgentUnknownUnicastFloodingClose(
		p.VxlanAgentUnknownUnicastFlooding,
	)
}

func _VxlanAgentUnknownUnicastFloodingClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed vxlanagentunknownunicastflooding_bpfeb.o
var _VxlanAgentUnknownUnicastFloodingBytes []byte
